version: '3.8'

services:
  app:
    image: merlingeo/sencare-app:latest
    container_name: sencare-app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017/patients_db
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-network

  mongo:
    container_name: mongo
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge

